API support
amnezia-vpn/amnezia-client pull request #368
Opened 2023-10-13 00:45 UTC by pokamest

2023-10-23 14:25 UTC, tiaga commented on client/vpnconnection.cpp
> +#include "core/controllers/serverController.h"
Seems this typo leads to failed build and `<` `>` should be used.

2023-11-06 10:58 UTC, useribs commented on client/protocols/openvpnprotocol.cpp
> +            "--management-client" , "--log", "/Users/nethius/Documents/git/log"
Looks suspicious, by mistake?

2023-11-06 11:14 UTC, outspace commented on client/ui/controllers/importController.cpp
> +    qDebug() << config;
please don't write config into the log file, it can contain sensitive data

2023-12-12 15:51 UTC, Noxius87 requested changes
Protocols are not switched in the protocol selection menu when switching from the main screen

2023-12-13 07:21 UTC, Nethius commented
> Protocols are not switched in the protocol selection menu when switching from the main screen

fixed

2023-12-13 11:43 UTC, Noxius87 approved these changes

2023-12-14 12:15 UTC, merged