Replace sftp with scp  #428
amnezia-vpn/amnezia-client pull request #602
Opened 2024-02-16 22:20 UTC by dimov96

Replacing the libssh::Client::sftpFileCopy  wtih libssh::Client::scpFileCopy.

2024-02-17 17:55 UTC, Nethius approved these changes

2024-02-18 14:57 UTC, pokamest requested changes

2024-02-18 14:57 UTC, pokamest commented on client/configurators/openvpn_configurator.cpp
> +            *errorCode = ErrorCode::OpenVpnUnknownError;
OpenVpnUnknownError is not suitable for this case, this error is not related to OpenVPN by itself. It's better to define new error codes if necessary

2024-02-18 14:57 UTC, pokamest commented on client/core/sshclient.cpp
> +            return closeScpSession();
Since we started refactoring, please improve error handling part, add new error codes if necessary.
`closeScpSession()` error code will be returned instead of actual error which we can retrieve using `ssh_get_error`

2024-02-18 14:57 UTC, pokamest commented on client/core/sshclient.cpp
> +            return closeScpSession();
Looks like you need to review and simplify whole scpFileCopy logic.
For example, closeScpSession() missing in some function exit conditions, but QFile fin not necessary to close at all.

2024-02-26 11:59 UTC, Nethius approved these changes

2024-03-05 20:51 UTC, pokamest approved these changes

2024-03-06 01:24 UTC, merged

2025-07-13 09:21 UTC, Yunir commented on client/core/defs.h
> +        UnspecifiedError = 1203,
The documentation does not contain them in https://docs.amnezia.org/troubleshooting/error-codes/
I face 1200 and don't know now how can I resolve it

2025-07-13 09:26 UTC, Yunir commented on client/core/defs.h
> +        UnspecifiedError = 1203,
it helped to restart the amnezia-client and try to setup the vpn on vps one more time.