Add in-app screenshot preventing
amnezia-vpn/amnezia-client pull request #606
Opened 2024-02-17 22:57 UTC by isamnezia

2024-02-19 14:23 UTC, pokamest requested changes

2024-02-19 14:23 UTC, pokamest commented on client/platforms/ios/ScreenProtection.swift
> +//#else
Please cleanup

2024-02-19 14:23 UTC, pokamest commented on client/ui/qml/Pages2/PageHome.qml
> +            Component.onCompleted: {
It shouldn't be called here.
Also required refactoring for the Android part in the SettingsController::SettingsController

2024-03-02 21:22 UTC, albexk commented on client/amnezia_application.cpp
> +    m_settingsController->toggleScreenshotsEnabled(m_settingsController->isScreenshotsEnabled());
Is it possible to move this to the generic IOS initialization block above (line 121)?

2024-03-03 16:09 UTC, albexk approved these changes

2024-03-05 23:35 UTC, pokamest approved these changes

2024-03-05 23:56 UTC, pokamest requested changes

2024-03-05 23:56 UTC, pokamest commented on client/platforms/ios/QtAppDelegate.mm
>  }
Do we need a cleanup after deleting these strings?

2024-03-05 23:56 UTC, pokamest commented on client/platforms/ios/QtAppDelegate.mm
> -    [_screen removeFromSuperview];
Do we need a cleanup after deleting these strings?

2024-03-06 01:17 UTC, pokamest approved these changes

2024-03-06 01:18 UTC, merged