[macOS] Add checking background service before connect
amnezia-vpn/amnezia-client pull request #716
Opened 2024-03-28 16:22 UTC by fameowner99

Just check if background proccess is alive.
Also this method will work in linux so we can extend to check also on linux.
Didnt find working objective-c way to check background services permissions

2024-03-28 19:21 UTC, Nethius requested changes

2024-03-28 19:21 UTC, Nethius commented on client/vpnconnection.cpp
> +    if (!MacOSUtils::isBackgroundServicesEnabled())
please move this check to ConnectionController

2024-05-02 13:00 UTC, lunardunno approved these changes

2024-05-10 09:05 UTC, Nethius approved these changes

2024-05-10 10:05 UTC, pokamest approved these changes

2024-05-10 10:06 UTC, merged